version: 2

models:
  - name: stg_steam_store_daily
    columns:
      - name: appid
        tests:
          - not_null

  - name: stg_steam_app_types
    columns:
      - name: appid
        tests:
          - not_null

  - name: stg_steam_game_online
    columns:
      - name: appid
        tests:
          - not_null

  - name: stg_steam_twitch_viewers
    columns:
      - name: appid
        tests:
          - not_null

  - name: stg_steam_twitch_channels
    columns:
      - name: appid
        tests:
          - not_null
